version: "3"
services:
  api:
    container_name: api
    build:
      context: packages/api
      dockerfile: Dockerfile
    environment:
      - IZG_ENDPOINT_CERT_DIR_PATH=/certs
  ui:
    container_name: ui
    build:
      context: packages/ui
      dockerfile: Dockerfile
    environment:
      - IZG_ENDPOINT_CERT_DIR_PATH=/certs
volumes:
  certs:
