name: Docker Image CI

on:
  push:
    branches: [ "mvp" ]
  pull_request:
    branches: [ "mvp" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile.ui --tag izg-config-console-ui:$(date +%s)